language: node_js
node_js:
  - "node"
install:
  - yarn
script:
  - yarn lint
  - yarn test
deploy:
  skip_cleanup: true
  on:
    branch: master
  provider: script
  script:
    - yarn build && rm ./build/static/js/*.js.map && now build --public --name retrowave-redux --token $NOW_TOKEN && now alias --token $NOW_TOKEN --force
