export const START = '_START';
export const SUCCESS = '_SUCCESS';
export const FAIL = '_FAIL';

export const FIRST_LOAD = 'FIRST_LOAD';
export const SWITCH_TO_PREVIOUS_TRACK = 'SWITCH_TO_PREVIOUS_TRACK';
export const SWITCH_TO_NEXT_TRACK = 'SWITCH_TO_NEXT_TRACK';
export const LOAD_NEXT_TRACK = 'LOAD_NEXT_TRACK';
export const CHANGE_PLAY_STATUS = 'CHANGE_PLAY_STATUS';
export const CHANGE_TRACK_DURATION = 'CHANGE_TRACK_DURATION';
export const CHANGE_TRACK_POSITION = 'CHANGE_TRACK_POSITION';
export const CHANGE_VOLUME = 'CHANGE_VOLUME';
